import { Platform } from "@/types";

export const PLATFORMS: Platform[] = [
  {
    id: "mt5",
    name: "MetaTrader 5",
    category: "forex",
    hasApi: true,
    description: "Connect your MT5 trading account",
    logoColor: "#00B4D8",
  },
  {
    id: "mt4",
    name: "MetaTrader 4",
    category: "forex",
    hasApi: true,
    description: "Connect your MT4 trading account",
    logoColor: "#0078D4",
  },
  {
    id: "matchtrader",
    name: "MatchTrader",
    category: "forex",
    hasApi: true,
    description: "Connect your MatchTrader account",
    logoColor: "#FF6B35",
  },
  {
    id: "ctrader",
    name: "cTrader",
    category: "forex",
    hasApi: true,
    description: "Connect your cTrader account",
    logoColor: "#4CAF50",
  },
  {
    id: "dxtrade",
    name: "DXTrade",
    category: "forex",
    hasApi: true,
    description: "Connect your DXTrade account",
    logoColor: "#9C27B0",
  },
  {
    id: "tradelocker",
    name: "TradeLocker",
    category: "forex",
    hasApi: true,
    description: "Connect your TradeLocker account",
    logoColor: "#FF9800",
  },
  {
    id: "exness",
    name: "Exness",
    category: "forex",
    hasApi: true,
    description: "Connect your Exness trading account",
    logoColor: "#0066FF",
  },
  {
    id: "binance",
    name: "Binance",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#F0B90B",
  },
  {
    id: "bybit",
    name: "Bybit",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#F7A600",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#0052FF",
  },
  {
    id: "kraken",
    name: "Kraken",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#7B61FF",
  },
  {
    id: "ibkr",
    name: "Interactive Brokers",
    category: "multi",
    hasApi: true,
    description: "Connect via TWS or IB Gateway",
    logoColor: "#E31837",
  },
  {
    id: "maven",
    name: "Maven Trading",
    category: "prop",
    hasApi: true,
    description: "Connect your Maven Trading account",
    logoColor: "#00C853",
  },
  {
    id: "ftmo",
    name: "FTMO",
    category: "prop",
    hasApi: true,
    description: "Connect your FTMO account",
    logoColor: "#FFD600",
  },
  {
    id: "fundednext",
    name: "Funded Next",
    category: "prop",
    hasApi: true,
    description: "Connect your Funded Next account",
    logoColor: "#00BFA5",
  },
  {
    id: "myfundedfx",
    name: "MyFundedFX",
    category: "prop",
    hasApi: true,
    description: "Connect your MyFundedFX account",
    logoColor: "#651FFF",
  },
  {
    id: "fundedtrader",
    name: "The Funded Trader",
    category: "prop",
    hasApi: true,
    description: "Connect your Funded Trader account",
    logoColor: "#FF6D00",
  },
  {
    id: "topstep",
    name: "TopStep",
    category: "prop",
    hasApi: true,
    description: "Connect your TopStep account",
    logoColor: "#2979FF",
  },
  {
    id: "e8funding",
    name: "E8 Funding",
    category: "prop",
    hasApi: true,
    description: "Connect your E8 Funding account",
    logoColor: "#00E676",
  },
  {
    id: "surgetrader",
    name: "Surge Trading",
    category: "prop",
    hasApi: true,
    description: "Connect your Surge Trading account",
    logoColor: "#FF1744",
  },
  {
    id: "manual",
    name: "Manual Account",
    category: "multi",
    hasApi: false,
    description: "Add trades manually",
    logoColor: "#6B7280",
  },
];

export const BROKER_SERVERS: Record<string, string[]> = {
  mt5: [
    "ICMarketsSC-MT5",
    "ICMarketsSC-MT5-2",
    "Pepperstone-MT5",
    "Pepperstone-MT5-2",
    "FPMarkets-Live",
    "XMGlobal-MT5",
    "Exness-MT5",
    "Exness-MT5-2",
    "RoboForex-MT5",
    "Tickmill-MT5",
    "FxPro-MT5",
    "Axiory-MT5",
    "NordFX-MT5",
    "FBS-MT5",
    "Alpari-MT5",
    "JustMarkets-MT5",
    "GlobalMarkets-MT5",
    "LiteFinance-MT5",
    "ICMarkets-Demo",
    "ICMarketsSC-Demo-MT5",
    "Pepperstone-Demo",
    "FPMarkets-Demo",
    "XMGlobal-Demo",
    "Exness-Demo",
    "MetaQuotes-Demo",
  ],
  mt4: [
    "ICMarketsSC-MT4",
    "ICMarketsSC-MT4-2",
    "Pepperstone-MT4",
    "Pepperstone-MT4-2",
    "FPMarkets-Live",
    "XMGlobal-MT4",
    "Exness-MT4",
    "RoboForex-MT4",
    "Tickmill-MT4",
    "FxPro-MT4",
    "FBS-MT4",
    "Alpari-MT4",
    "JustMarkets-MT4",
    "LiteFinance-MT4",
    "ICMarkets-Demo",
    "ICMarketsSC-Demo-MT4",
    "Pepperstone-Demo",
    "MetaQuotes-Demo",
  ],
  ctrader: [
    "Pepperstone-Edge",
    "ICMarkets-cTrader",
    "FPMarkets-cTrader",
    "FXCM-cTrader",
    "Saxo-cTrader",
  ],
  exness: [
    "Exness-MT5",
    "Exness-MT5-2",
    "Exness-MT5-Real",
    "Exness-MT5-Real2",
    "Exness-MT5-Demo",
    "Exness-MT5-Demo2",
    "Exness-MT4",
    "Exness-MT4-2",
    "Exness-MT4-Real",
    "Exness-MT4-Real2",
    "Exness-MT4-Demo",
    "Exness-MT4-Demo2",
    "Exness-Standard",
    "Exness-Standard-Demo",
    "Exness-Pro",
    "Exness-Pro-Demo",
    "Exness-RawSpread",
    "Exness-RawSpread-Demo",
    "Exness-Zero",
    "Exness-Zero-Demo",
  ],
  matchtrader: [
    "MatchTrader-Live",
    "MatchTrader-Demo",
  ],
  dxtrade: [
    "DXTrade-Live",
    "DXTrade-Demo",
    "ThinkMarkets-DXTrade",
  ],
  tradelocker: [
    "TradeLocker-Live",
    "TradeLocker-Demo",
  ],
  maven: [
    "Maven-Live",
    "Maven-Demo",
    "Maven-MT5",
    "Maven-MT4",
  ],
  ftmo: [
    "FTMO-MT5",
    "FTMO-MT4",
    "FTMO-Live",
    "FTMO-Demo",
    "FTMO-Scaling",
  ],
  fundednext: [
    "FundedNext-MT5",
    "FundedNext-MT4",
    "FundedNext-Live",
    "FundedNext-Demo",
    "FundedNext-Evaluation",
    "FundedNext-Express",
  ],
  myfundedfx: [
    "MyFundedFX-MT5",
    "MyFundedFX-MT4",
    "MyFundedFX-Live",
    "MyFundedFX-Demo",
  ],
  fundedtrader: [
    "FundedTrader-MT5",
    "FundedTrader-MT4",
    "FundedTrader-Live",
    "FundedTrader-Demo",
    "FundedTrader-Standard",
    "FundedTrader-Rapid",
  ],
  topstep: [
    "TopStep-MT5",
    "TopStep-MT4",
    "TopStep-Live",
    "TopStep-Demo",
    "TopStep-Futures",
  ],
  e8funding: [
    "E8Funding-MT5",
    "E8Funding-MT4",
    "E8Funding-Live",
    "E8Funding-Demo",
  ],
  surgetrader: [
    "SurgeTrader-MT5",
    "SurgeTrader-MT4",
    "SurgeTrader-Live",
    "SurgeTrader-Demo",
  ],
};

export const PLATFORM_FIELDS: Record<string, { label: string; placeholder: string; required: boolean; type?: string }[]> = {
  mt5: [
    { label: "Account Name", placeholder: "My MT5 Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  mt4: [
    { label: "Account Name", placeholder: "My MT4 Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  binance: [
    { label: "Account Name", placeholder: "My Binance Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  bybit: [
    { label: "Account Name", placeholder: "My Bybit Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  coinbase: [
    { label: "Account Name", placeholder: "My Coinbase Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  kraken: [
    { label: "Account Name", placeholder: "My Kraken Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  ctrader: [
    { label: "Account Name", placeholder: "My cTrader Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  exness: [
    { label: "Account Name", placeholder: "My Exness Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  matchtrader: [
    { label: "Account Name", placeholder: "My MatchTrader Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  dxtrade: [
    { label: "Account Name", placeholder: "My DXTrade Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  tradelocker: [
    { label: "Account Name", placeholder: "My TradeLocker Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  ibkr: [
    { label: "Account Name", placeholder: "My IBKR Account", required: false },
    { label: "Account Number", placeholder: "IBKR account number", required: true },
    { label: "Username", placeholder: "IBKR username", required: true },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  maven: [
    { label: "Account Name", placeholder: "My Maven Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  ftmo: [
    { label: "Account Name", placeholder: "My FTMO Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  fundednext: [
    { label: "Account Name", placeholder: "My Funded Next Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  myfundedfx: [
    { label: "Account Name", placeholder: "My FundedFX Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  fundedtrader: [
    { label: "Account Name", placeholder: "My Funded Trader Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  topstep: [
    { label: "Account Name", placeholder: "My TopStep Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  e8funding: [
    { label: "Account Name", placeholder: "My E8 Funding Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  surgetrader: [
    { label: "Account Name", placeholder: "My Surge Trading Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  manual: [
    { label: "Account Name", placeholder: "My Trading Account", required: false },
    { label: "Broker Name", placeholder: "Broker name", required: true },
    { label: "Account Type", placeholder: "Live or Demo", required: true },
    { label: "Initial Balance", placeholder: "10000", required: true, type: "number" },
    { label: "Currency", placeholder: "USD", required: true },
  ],
};
