import { Platform } from "@/types";

export const PLATFORMS: Platform[] = [
  {
    id: "mt5",
    name: "MetaTrader 5",
    category: "forex",
    hasApi: true,
    description: "Connect your MT5 trading account",
    logoColor: "#00B4D8",
  },
  {
    id: "mt4",
    name: "MetaTrader 4",
    category: "forex",
    hasApi: true,
    description: "Connect your MT4 trading account",
    logoColor: "#0078D4",
  },
  {
    id: "matchtrader",
    name: "MatchTrader",
    category: "forex",
    hasApi: true,
    description: "Connect your MatchTrader account",
    logoColor: "#FF6B35",
  },
  {
    id: "ctrader",
    name: "cTrader",
    category: "forex",
    hasApi: true,
    description: "Connect your cTrader account",
    logoColor: "#4CAF50",
  },
  {
    id: "dxtrade",
    name: "DXTrade",
    category: "forex",
    hasApi: true,
    description: "Connect your DXTrade account",
    logoColor: "#9C27B0",
  },
  {
    id: "tradelocker",
    name: "TradeLocker",
    category: "forex",
    hasApi: true,
    description: "Connect your TradeLocker account",
    logoColor: "#FF9800",
  },
  {
    id: "binance",
    name: "Binance",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#F0B90B",
  },
  {
    id: "bybit",
    name: "Bybit",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#F7A600",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#0052FF",
  },
  {
    id: "kraken",
    name: "Kraken",
    category: "crypto",
    hasApi: true,
    description: "Connect via API keys",
    logoColor: "#7B61FF",
  },
  {
    id: "ibkr",
    name: "Interactive Brokers",
    category: "multi",
    hasApi: true,
    description: "Connect via TWS or IB Gateway",
    logoColor: "#E31837",
  },
  {
    id: "manual",
    name: "Manual Account",
    category: "multi",
    hasApi: false,
    description: "Add trades manually",
    logoColor: "#6B7280",
  },
];

export const BROKER_SERVERS: Record<string, string[]> = {
  mt5: [
    "ICMarketsSC-MT5",
    "ICMarketsSC-MT5-2",
    "Pepperstone-MT5",
    "Pepperstone-MT5-2",
    "FPMarkets-Live",
    "XMGlobal-MT5",
    "Exness-MT5",
    "Exness-MT5-2",
    "RoboForex-MT5",
    "Tickmill-MT5",
    "FxPro-MT5",
    "Axiory-MT5",
    "NordFX-MT5",
    "FBS-MT5",
    "Alpari-MT5",
    "JustMarkets-MT5",
    "GlobalMarkets-MT5",
    "LiteFinance-MT5",
    "ICMarkets-Demo",
    "ICMarketsSC-Demo-MT5",
    "Pepperstone-Demo",
    "FPMarkets-Demo",
    "XMGlobal-Demo",
    "Exness-Demo",
    "MetaQuotes-Demo",
  ],
  mt4: [
    "ICMarketsSC-MT4",
    "ICMarketsSC-MT4-2",
    "Pepperstone-MT4",
    "Pepperstone-MT4-2",
    "FPMarkets-Live",
    "XMGlobal-MT4",
    "Exness-MT4",
    "RoboForex-MT4",
    "Tickmill-MT4",
    "FxPro-MT4",
    "FBS-MT4",
    "Alpari-MT4",
    "JustMarkets-MT4",
    "LiteFinance-MT4",
    "ICMarkets-Demo",
    "ICMarketsSC-Demo-MT4",
    "Pepperstone-Demo",
    "MetaQuotes-Demo",
  ],
  ctrader: [
    "Pepperstone-Edge",
    "ICMarkets-cTrader",
    "FPMarkets-cTrader",
    "FXCM-cTrader",
    "Saxo-cTrader",
  ],
  matchtrader: [
    "MatchTrader-Live",
    "MatchTrader-Demo",
  ],
  dxtrade: [
    "DXTrade-Live",
    "DXTrade-Demo",
    "ThinkMarkets-DXTrade",
  ],
  tradelocker: [
    "TradeLocker-Live",
    "TradeLocker-Demo",
  ],
};

export const PLATFORM_FIELDS: Record<string, { label: string; placeholder: string; required: boolean; type?: string }[]> = {
  mt5: [
    { label: "Account Name", placeholder: "My MT5 Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  mt4: [
    { label: "Account Name", placeholder: "My MT4 Account", required: false },
    { label: "Broker Server", placeholder: "Search servers...", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  binance: [
    { label: "Account Name", placeholder: "My Binance Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  bybit: [
    { label: "Account Name", placeholder: "My Bybit Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  coinbase: [
    { label: "Account Name", placeholder: "My Coinbase Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  kraken: [
    { label: "Account Name", placeholder: "My Kraken Account", required: false },
    { label: "API Key", placeholder: "Enter API key", required: true },
    { label: "API Secret", placeholder: "Enter API secret", required: true, type: "password" },
  ],
  ctrader: [
    { label: "Account Name", placeholder: "My cTrader Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  matchtrader: [
    { label: "Account Name", placeholder: "My MatchTrader Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  dxtrade: [
    { label: "Account Name", placeholder: "My DXTrade Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  tradelocker: [
    { label: "Account Name", placeholder: "My TradeLocker Account", required: false },
    { label: "Broker Server", placeholder: "Select server", required: true },
    { label: "Login ID", placeholder: "Account number", required: true, type: "number" },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  ibkr: [
    { label: "Account Name", placeholder: "My IBKR Account", required: false },
    { label: "Account Number", placeholder: "IBKR account number", required: true },
    { label: "Username", placeholder: "IBKR username", required: true },
    { label: "Password", placeholder: "Trading password", required: true, type: "password" },
  ],
  manual: [
    { label: "Account Name", placeholder: "My Trading Account", required: false },
    { label: "Broker Name", placeholder: "Broker name", required: true },
    { label: "Account Type", placeholder: "Live or Demo", required: true },
    { label: "Initial Balance", placeholder: "10000", required: true, type: "number" },
    { label: "Currency", placeholder: "USD", required: true },
  ],
};
